<?php
return array (
  1 => 
  array (
    'id' => '1',
    'catid' => '9',
    'typeid' => '0',
    'title' => '婚纱礼服',
    'style' => '',
    'thumb' => '',
    'keywords' => '婚纱礼服',
    'description' => '撒大声地韩国汽车说不出开始蹦擦擦成本价是不成熟卡车',
    'posids' => '0',
    'url' => 'http://localhost/response/index.php?m=content&c=index&a=show&catid=9&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1493025358',
    'updatetime' => '1493025413',
    'hitsid' => 'c-1-1',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  2 => 
  array (
    'id' => '2',
    'catid' => '9',
    'typeid' => '0',
    'title' => '各个娃和爱护她',
    'style' => '',
    'thumb' => '',
    'keywords' => '各个 村上春树',
    'description' => '第五位法国人 个人他还特意介绍硬件安徽省让他忽然他  gear呀让他一人同意让他favorite特然',
    'posids' => '0',
    'url' => 'http://localhost/response/index.php?m=content&c=index&a=show&catid=9&id=2',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1493025418',
    'updatetime' => '1493025484',
    'hitsid' => 'c-1-2',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>